### ISSUE TITLE
Please fixup package.json license

### ISSUE THREAD

**Issue by dantran** [rauchg/ms.js#58]
it should be like this

  "license": {
    "type": "MIT",
    "url": "https://github.com/rauchg/ms.js/blob/master/LICENSE"
  },

**Comment by andrew-oxenburgh** [comment]
No it shouldn't.

According to https://docs.npmjs.com/files/package.json the right way is ```{ "license" : "MIT" }``` which is how I'm seeing it right now.

**Comment by dantran** [comment]
works per spec
